version: "3.9"

services:
  signal-api:
    image: bbernhard/signal-cli-rest-api:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:8085:8080"   # host 8085 -> container 8080 (localhost only)
    env_file:
      - .env                  # 👈 this injects .env into the container’s environment
    environment:
      MODE: "${SIGNAL_API_MODE:-native}"
      TZ: "${TZ:-UTC}"
    volumes:
      - "${SIGNAL_DATA_DIR:-./signal-cli}:/home/.local/share/signal-cli"

  notifier-gateway:
    build: ./notifier-gateway
    restart: unless-stopped
    env_file:
      - .env                  # 👈 this injects .env into the container’s environment 
    environment:
      SIGNAL_API_BASE: "http://signal-api:8080"
      SIGNAL_NUMBER: "${SIGNAL_NUMBER}"
      GATEWAY_TOKEN: "${GATEWAY_TOKEN}"
      TZ: "${TZ:-UTC}"
    ports:
      - "127.0.0.1:${GATEWAY_PORT:-8787}:8787"  # host-only
    depends_on:
      - signal-api
